# Test Fused_CNN_ResNet50_CNN_ResNet50_Averaging (RoHL)
# python main.py --config-file "configs/custom/experiment_16.yaml" --eval-only --data-dir [options]
MODEL:
  TYPE: "AveragingModel"
  NAME: "Fused_CNN_ResNet50_CNN_ResNet50_Averaging"
  MODEL_DIR: "/kaggle/input/train-high-freq-cnndet/pytorch/default/1"
  MODEL_NAME: "model-best.pth.tar"

DATASET:
  NAME: "NTIRE2026Dataset"
  DATA_DIR: "/kaggle/input/ntire-validation-dataset-update-322026/val_images/val_images"
  NUM_CLASSES: 2

DATALOADER:
  BATCH_SIZE: 128

TRANSFORM:
  TRANSFORMS: ["resize", "to_tensor", "normalize"]
  NORMALIZE_BACKBONE: True
  INTERPOLATION_MODE: "bilinear"
  INPUT_SIZE: (224, 224)
  NO_TRANSFORM_TEST: False

TRAINER:
  TYPE: 4
  USE_CUDA: True
  IS_TRAIN: False
  NO_TEST: False

RoHL:
  USE_JSD: False
  TEST_MODE: "test_0"

EVALUATOR:
  TYPE: 1
