# Train Fused_CNN_ResNet50_CNN_ResNet50_Averaging on ProGAN following RoHL
# python main.py --config-file "configs/custom/experiment_13.yaml" --no-tf-test True --resume False
MODEL:
  TYPE: "AveragingModel"
  NAME: "Fused_CNN_ResNet50_CNN_ResNet50_Averaging"
  MODEL_DIR: "/kaggle/input/train-low-freq/pytorch/default/1"
  MODEL_NAME: "model-best.pth.tar"
  RESUME: True
  BACKBONE:
    PRETRAINED: False
    FREEZE: False
    RESNET50_AM_WEIGHTS: "/kaggle/input/augmix-resnet50-imagenet/pytorch/default/1/checkpoint.pth.tar"

DATASET:
  NAME: "CNNSpot"
  DATA_DIR: "/kaggle/input/cnnspot/cnn_spot"
  NUM_CLASSES: 2

DATALOADER:
  BATCH_SIZE: 32

TRANSFORM:
  TRANSFORMS: ["resize", "to_tensor", "normalize"]
  NORMALIZE_BACKBONE: True
  INTERPOLATION_MODE: "bilinear"
  INPUT_SIZE: (224, 224)
  NO_TRANSFORM_TEST: True # NO_TRANSFORM_TEST does not matter because TRANSFORMS is basic

TRAINER:
  TYPE: 3
  USE_CUDA: True
  IS_TRAIN: True
  NUM_EPOCHS: 3
  NO_TEST: False
  TEST_FINAL_MODEL: "best_val"
  OPTIM:
    NAME: "sgd"
    LR: 0.002
    STEPSIZE: [20]

RoHL:
  STAGE: 2
  USE_JSD: False

EVALUATOR:
  TYPE: 1
